# Site settings
author: Marie C. Burns
title: The Adjustment
header-img: img/home-bg.png
email: mcburns2222@gmail.com
copyright_name: Marie C. Burns
description: > # this means to ignore newlines until "baseurl:"
  Learning new ways to think and problem solve
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ceci2222

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
